/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "Sha256".
 */
export type Sha256 = string;
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "Uuid".
 */
export type Uuid = string;
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "Timestamp".
 */
export type Timestamp = string;

export interface YAWNContractsV1 {
  constitution?: YawnConstitutionV1;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "YawnConstitutionV1".
 */
export interface YawnConstitutionV1 {
  schemaVersion: "yawn.constitution.v1";
  canonicalLoop: ["signal", "orientation", "choice", "move", "proof", "update"];
  upperOntology: [
    "actor_agent",
    "agent_space",
    "arena",
    "observation_claim",
    "lacuna",
    "intent_goal_value",
    "boundary_authority",
    "move_action",
    "evidence_outcome_proof",
    "update_revision"
  ];
  aiOutputPolicy: "proposal_until_authenticated_human_approval";
  targetPolicy: "optional";
  authorityPolicy: "child_subset_of_parent_plus_explicit_grant";
  proofPolicy: "preconditions_prediction_postconditions_verifier_falsifier";
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "AgentSpace".
 */
export interface AgentSpace {
  id: Uuid;
  ownerPrincipalId: Uuid;
  slug: string;
  title: string;
  constitutionVersion: "yawn.constitution.v1";
  revision: number;
  stateSha256?: Sha256 | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "Arena".
 */
export interface Arena {
  id: Uuid;
  agentSpaceId: Uuid;
  slug: string;
  title: string;
  status: "proposed" | "accepted" | "rejected" | "superseded";
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "YawnState".
 */
export interface YawnState {
  id: Uuid;
  agentSpaceId: Uuid;
  arenaId: Uuid | null;
  parentYawnId: Uuid | null;
  title: string;
  lacuna: string;
  target: {
    [k: string]: unknown;
  } | null;
  authority: {
    [k: string]: unknown;
  };
  revision: number;
  status: "proposed" | "accepted" | "rejected" | "superseded";
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "SourceRecord".
 */
export interface SourceRecord {
  id: Uuid;
  importId: Uuid;
  sourceKey: string;
  sourceKind: string;
  assertedBy: string;
  authorRole: "human" | "assistant" | "system" | "tool" | "unknown";
  sourceSha256: Sha256;
  occurredAt?: Timestamp | null;
  localOnly: boolean;
  metadata: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "SourceSpan".
 */
export interface SourceSpan {
  sourceId: string;
  conversationId: string | null;
  messageId: string | null;
  nodeId: string | null;
  contentPart: number | null;
  startCharacter: number;
  endCharacter: number;
  sourceSha256: Sha256;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "OrientationAtom".
 */
export interface OrientationAtom {
  id: string;
  agentSpaceId: string;
  arenaId: string | null;
  yawnId: string | null;
  epistemicKind:
    | "observation"
    | "claim"
    | "lacuna"
    | "intent"
    | "goal"
    | "value"
    | "boundary"
    | "action"
    | "evidence"
    | "outcome"
    | "revision";
  text: string;
  assertedBy: string;
  /**
   * @minItems 1
   */
  sourceSpans: [SourceSpan, ...SourceSpan[]];
  confidence: number;
  status: "proposed";
  inferenceRunId: string | null;
  createdAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "YawnCandidate".
 */
export interface YawnCandidate {
  id: string;
  agentSpaceId: string;
  title: string;
  arenaId: string | null;
  proposedParentYawnId: string | null;
  lacuna: string;
  intent: string | null;
  /**
   * @minItems 1
   */
  evidenceAtomIds: [string, ...string[]];
  promotionReasons: (
    | "persistent"
    | "consequential_lacuna"
    | "authority_boundary"
    | "requires_proof"
    | "cross_arena_recurrence"
    | "explicit_human_request"
  )[];
  confidence: number;
  status: "proposed";
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ChangeProposal".
 */
export interface ChangeProposal {
  id: Uuid;
  agentSpaceId: Uuid;
  proposalType: "atom" | "arena" | "yawn" | "link" | "merge" | "split" | "promote" | "demote" | "revision";
  targetId: Uuid | null;
  payload: {
    [k: string]: unknown;
  };
  sourceAtomIds: Uuid[];
  confidence: number;
  status: "proposed" | "accepted" | "rejected" | "superseded";
  createdAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "AuthorityGrant".
 */
export interface AuthorityGrant {
  id: Uuid;
  parentAuthorityId: Uuid | null;
  principalId: string;
  scope: {
    [k: string]: unknown;
  };
  capabilities: string[];
  approvedBy: Uuid;
  approvedAt: Timestamp;
  revokedAt: Timestamp | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ImportGrant".
 */
export interface ImportGrant {
  id: Uuid;
  importId: Uuid;
  sourceSha256: Sha256;
  provider: "openai";
  allowedModels: string[];
  allowedReasoningEfforts: string[];
  remoteSourceTransferApproved: true;
  budgetId: Uuid;
  approvedBy: Uuid;
  approvedAt: Timestamp;
  revokedAt: Timestamp | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "PricingSnapshot".
 */
export interface PricingSnapshot {
  id: string;
  currency: "USD";
  effectiveAt: Timestamp;
  sourceUrl: string;
  batchDiscountBasisPoints: number;
  models: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "RunBudget".
 */
export interface RunBudget {
  id: Uuid;
  runId: Uuid;
  currency: "USD";
  limitMicrousd: number;
  softStopMicrousd: number;
  actualMicrousd: number;
  openReservationMicrousd: number;
  pricingSnapshotId: string;
  status: "active" | "soft_stopped" | "hard_stopped" | "closed" | "revoked";
  authorizedBy: Uuid;
  authorizedAt: Timestamp;
  supersedesBudgetId: Uuid | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "CostEstimate".
 */
export interface CostEstimate {
  pricingSnapshotId: string;
  model: string;
  batch: boolean;
  inputTokens: number;
  cachedInputTokens: number;
  expectedOutputTokens: number;
  maximumOutputTokens: number;
  minimumMicrousd: number;
  expectedMicrousd: number;
  worstCaseMicrousd: number;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "CostReservation".
 */
export interface CostReservation {
  id: Uuid;
  budgetId: Uuid;
  requestKey: string;
  estimate: CostEstimate;
  reservedMicrousd: number;
  actualMicrousd: number | null;
  providerRequestId: string | null;
  status: "open" | "reconciled" | "released" | "failed_unknown_usage";
  createdAt: Timestamp;
  reconciledAt: Timestamp | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "UsageLedgerEntry".
 */
export interface UsageLedgerEntry {
  id: Uuid;
  budgetId: Uuid;
  reservationId: Uuid;
  model: string;
  inputTokens: number;
  cachedInputTokens: number;
  outputTokens: number;
  reasoningTokens: number;
  actualMicrousd: number;
  providerRequestId: string;
  recordedAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ModelRunReceipt".
 */
export interface ModelRunReceipt {
  id: Uuid;
  importId: Uuid;
  reservationId: Uuid;
  provider: "openai";
  model: string;
  reasoningEffort: string;
  mode: "standard" | "pro";
  providerBatchId: string;
  workflowRunId: string;
  inputFileId: string;
  outputFileId: string | null;
  usage: UsageLedgerEntry | null;
  deletionReceiptIds: Uuid[];
  status: "submitted" | "in_progress" | "completed" | "failed" | "expired" | "cancelled" | "usage_unknown";
  createdAt: Timestamp;
  completedAt: Timestamp | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "YawnEvent".
 */
export interface YawnEvent {
  id: Uuid;
  agentSpaceId: Uuid;
  yawnId: Uuid | null;
  streamKey: string;
  revision: number;
  eventType: string;
  actorId: string;
  proposalId: Uuid | null;
  payload: {
    [k: string]: unknown;
  };
  previousStateSha256: Sha256 | null;
  resultingStateSha256: Sha256;
  occurredAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ProofReceipt".
 */
export interface ProofReceipt {
  id: Uuid;
  yawnId: Uuid;
  preconditions: {
    [k: string]: unknown;
  };
  prediction: string;
  postconditions: {
    [k: string]: unknown;
  };
  verifier: string;
  falsifier: string;
  sourceRefs: SourceSpan[];
  status: "waiting" | "passed" | "failed" | "blocked";
  createdAt: Timestamp;
}
