/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "Sha256".
 */
export type Sha256 = string;
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "Uuid".
 */
export type Uuid = string;
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "Timestamp".
 */
export type Timestamp = string;

export interface YAWNContractsV1 {
  constitution?: YawnConstitutionV1;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "YawnConstitutionV1".
 */
export interface YawnConstitutionV1 {
  schemaVersion: "yawn.constitution.v1";
  canonicalLoop: ["signal", "orientation", "choice", "move", "proof", "update"];
  upperOntology: [
    "actor_agent",
    "agent_space",
    "arena",
    "observation_claim",
    "lacuna",
    "intent_goal_value",
    "boundary_authority",
    "move_action",
    "evidence_outcome_proof",
    "update_revision"
  ];
  aiOutputPolicy: "proposal_until_authenticated_human_approval";
  targetPolicy: "optional";
  authorityPolicy: "child_subset_of_parent_plus_explicit_grant";
  proofPolicy: "preconditions_prediction_postconditions_verifier_falsifier";
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "AgentSpace".
 */
export interface AgentSpace {
  id: Uuid;
  ownerPrincipalId: Uuid;
  slug: string;
  title: string;
  constitutionVersion: "yawn.constitution.v1";
  revision: number;
  stateSha256?: Sha256 | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "Arena".
 */
export interface Arena {
  id: Uuid;
  agentSpaceId: Uuid;
  slug: string;
  title: string;
  status: "proposed" | "accepted" | "rejected" | "superseded";
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "YawnState".
 */
export interface YawnState {
  id: Uuid;
  agentSpaceId: Uuid;
  arenaId: Uuid | null;
  parentYawnId: Uuid | null;
  title: string;
  lacuna: string;
  target: {
    [k: string]: unknown;
  } | null;
  authority: {
    [k: string]: unknown;
  };
  revision: number;
  status: "proposed" | "accepted" | "rejected" | "superseded";
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "SourceRecord".
 */
export interface SourceRecord {
  id: Uuid;
  importId: Uuid;
  sourceKey: string;
  sourceKind: string;
  assertedBy: string;
  authorRole: "human" | "assistant" | "system" | "tool" | "unknown";
  sourceSha256: Sha256;
  occurredAt?: Timestamp | null;
  localOnly: boolean;
  metadata: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "SourceSpan".
 */
export interface SourceSpan {
  sourceId: string;
  conversationId: string | null;
  messageId: string | null;
  nodeId: string | null;
  contentPart: number | null;
  startCharacter: number;
  endCharacter: number;
  sourceSha256: Sha256;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "OrientationAtom".
 */
export interface OrientationAtom {
  id: string;
  agentSpaceId: string;
  arenaId: string | null;
  yawnId: string | null;
  epistemicKind:
    | "observation"
    | "claim"
    | "lacuna"
    | "intent"
    | "goal"
    | "value"
    | "boundary"
    | "action"
    | "evidence"
    | "outcome"
    | "revision";
  text: string;
  assertedBy: string;
  /**
   * @minItems 1
   */
  sourceSpans: [SourceSpan, ...SourceSpan[]];
  confidence: number;
  status: "proposed";
  inferenceRunId: string | null;
  createdAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "YawnCandidate".
 */
export interface YawnCandidate {
  id: string;
  agentSpaceId: string;
  title: string;
  arenaId: string | null;
  proposedParentYawnId: string | null;
  lacuna: string;
  intent: string | null;
  /**
   * @minItems 1
   */
  evidenceAtomIds: [string, ...string[]];
  promotionReasons: (
    | "persistent"
    | "consequential_lacuna"
    | "authority_boundary"
    | "requires_proof"
    | "cross_arena_recurrence"
    | "explicit_human_request"
  )[];
  confidence: number;
  status: "proposed";
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ChangeProposal".
 */
export interface ChangeProposal {
  id: Uuid;
  agentSpaceId: Uuid;
  proposalType: "atom" | "arena" | "yawn" | "link" | "merge" | "split" | "promote" | "demote" | "revision";
  targetId: Uuid | null;
  payload: {
    [k: string]: unknown;
  };
  sourceAtomIds: Uuid[];
  confidence: number;
  status: "proposed" | "accepted" | "rejected" | "superseded";
  createdAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "AuthorityGrant".
 */
export interface AuthorityGrant {
  id: Uuid;
  parentAuthorityId: Uuid | null;
  principalId: string;
  scope: {
    [k: string]: unknown;
  };
  capabilities: string[];
  approvedBy: Uuid;
  approvedAt: Timestamp;
  revokedAt: Timestamp | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ImportGrant".
 */
export interface ImportGrant {
  id: Uuid;
  importId: Uuid;
  sourceSha256: Sha256;
  provider: "openai";
  allowedModels: string[];
  allowedReasoningEfforts: string[];
  remoteSourceTransferApproved: true;
  budgetId: Uuid;
  approvedBy: Uuid;
  approvedAt: Timestamp;
  revokedAt: Timestamp | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "PricingSnapshot".
 */
export interface PricingSnapshot {
  id: string;
  currency: "USD";
  effectiveAt: Timestamp;
  sourceUrl: string;
  batchDiscountBasisPoints: number;
  models: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "RunBudget".
 */
export interface RunBudget {
  id: Uuid;
  runId: Uuid;
  currency: "USD";
  limitMicrousd: number;
  softStopMicrousd: number;
  actualMicrousd: number;
  openReservationMicrousd: number;
  pricingSnapshotId: string;
  status: "active" | "soft_stopped" | "hard_stopped" | "closed" | "revoked";
  authorizedBy: Uuid;
  authorizedAt: Timestamp;
  supersedesBudgetId: Uuid | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "CostEstimate".
 */
export interface CostEstimate {
  pricingSnapshotId: string;
  model: string;
  batch: boolean;
  inputTokens: number;
  cachedInputTokens: number;
  expectedOutputTokens: number;
  maximumOutputTokens: number;
  minimumMicrousd: number;
  expectedMicrousd: number;
  worstCaseMicrousd: number;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "CostReservation".
 */
export interface CostReservation {
  id: Uuid;
  budgetId: Uuid;
  requestKey: string;
  estimate: CostEstimate;
  reservedMicrousd: number;
  actualMicrousd: number | null;
  providerRequestId: string | null;
  status: "open" | "reconciled" | "released" | "failed_unknown_usage";
  createdAt: Timestamp;
  reconciledAt: Timestamp | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "UsageLedgerEntry".
 */
export interface UsageLedgerEntry {
  id: Uuid;
  budgetId: Uuid;
  reservationId: Uuid;
  model: string;
  inputTokens: number;
  cachedInputTokens: number;
  outputTokens: number;
  reasoningTokens: number;
  actualMicrousd: number;
  providerRequestId: string;
  recordedAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ModelRunReceipt".
 */
export interface ModelRunReceipt {
  id: Uuid;
  importId: Uuid;
  reservationId: Uuid;
  provider: "openai";
  model: string;
  reasoningEffort: string;
  mode: "standard" | "pro";
  providerBatchId: string;
  workflowRunId: string;
  inputFileId: string;
  outputFileId: string | null;
  usage: UsageLedgerEntry | null;
  deletionReceiptIds: Uuid[];
  status: "submitted" | "in_progress" | "completed" | "failed" | "expired" | "cancelled" | "usage_unknown";
  createdAt: Timestamp;
  completedAt: Timestamp | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "RecordRef".
 */
export interface RecordRef {
  kind:
    | "actor"
    | "principal"
    | "agent_space"
    | "arena"
    | "observation"
    | "yawn"
    | "source"
    | "proof"
    | "view"
    | "git_commit"
    | "question_proposal"
    | "art_brief"
    | "art_candidate"
    | "projection_feedback";
  id: string;
  revision?: number | null;
  stateSha256?: Sha256 | null;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ManualSourceRecordV1".
 */
export interface ManualSourceRecordV1 {
  id: Uuid;
  sourceKey: string;
  sourceKind: "manual_observation";
  assertedBy: string;
  authorRole: "human";
  sourceSha256: Sha256;
  occurredAt?: Timestamp | null;
  localOnly: boolean;
  metadata: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ObservationSourceSpanV1".
 */
export interface ObservationSourceSpanV1 {
  sourceRef: string;
  sourceSha256: Sha256;
  startCharacter: number;
  endCharacter: number;
  coordinate: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ObservationStateV1".
 */
export interface ObservationStateV1 {
  schemaVersion: "yawn.observation-state.v1";
  observationId: string;
  observerRef: string;
  agentSpaceRef: string;
  arenaRef: string | null;
  observedYawnRefs: string[];
  /**
   * @minItems 1
   */
  sourceSpans: [ObservationSourceSpanV1, ...ObservationSourceSpanV1[]];
  whatBecameAvailable: string;
  observerAdded: SourceStatementV1[];
  inferences: InferenceStatementV1[];
  conditions: string[];
  limits: string[];
  remainsOpen: string[];
  proofRefs: string[];
  epistemicStatus: "observed" | "reported" | "inferred" | "assumed" | "predicted" | "disputed" | "unknown";
  confidence: number;
  status: "accepted" | "superseded";
  revision: number;
  observedAt: Timestamp | null;
  recordedAt: Timestamp;
  updatedAt: Timestamp;
  previousStateSha256: Sha256 | null;
  extensions: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "SourceStatementV1".
 */
export interface SourceStatementV1 {
  text: string;
  assertedBy: string;
  epistemicStatus: "observed" | "reported" | "disputed" | "unknown";
  confidence: number;
  sourceSpanIndexes: number[];
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "InferenceStatementV1".
 */
export interface InferenceStatementV1 {
  text: string;
  assertedBy: string;
  epistemicStatus: "inferred" | "assumed" | "predicted" | "disputed" | "unknown";
  confidence: number;
  sourceSpanIndexes: number[];
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "RecordEventV1".
 */
export interface RecordEventV1 {
  schemaVersion: "yawn.record-event.v1";
  eventId: string;
  subjectRef: RecordRef;
  revision: number;
  eventType: string;
  actorRef: string;
  authorityStatus: "proposed" | "authorized" | "rejected";
  payload: {
    [k: string]: unknown;
  };
  previousStateSha256: Sha256 | null;
  resultingStateSha256: Sha256;
  occurredAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "RecordProofReceiptV1".
 */
export interface RecordProofReceiptV1 {
  schemaVersion: "yawn.record-proof-receipt.v1";
  receiptId: string;
  subjectRef: RecordRef;
  preconditions: {
    [k: string]: unknown;
  };
  prediction: string;
  postconditions: {
    [k: string]: unknown;
  };
  verifier: string;
  falsifier: string;
  sourceRefs: RecordRef[];
  status: "waiting" | "passed" | "failed" | "blocked" | "runner_unavailable";
  recordedAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ProjectionPreferenceV1".
 */
export interface ProjectionPreferenceV1 {
  schemaVersion: "yawn.projection-preference.v1";
  preferenceId: string;
  principalRef: string;
  scopeRef: {
    kind: "principal" | "agent_space" | "arena" | "yawn" | "observation" | "view";
    id: string;
    revision?: number | null;
    stateSha256?: Sha256 | null;
  };
  viewKind: string;
  fieldPath: string;
  operation: "set" | "reset";
  value: unknown;
  status: "accepted";
  revision: number;
  sourceEventRef: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "QuestionProposalV1".
 */
export interface QuestionProposalV1 {
  schemaVersion: "yawn.question-proposal.v1";
  questionProposalId: string;
  revision: number;
  observationRef: RecordRef & {
    kind?: "observation";
    revision: number;
    stateSha256: Sha256;
    [k: string]: unknown;
  };
  source: {
    fieldPath: string;
    verbatimText: string;
    sourceSpanIndexes: [];
  };
  text: string;
  transformation: "verbatim" | "organized";
  proposedBy: RecordRef & {
    kind?: "actor" | "principal";
    [k: string]: unknown;
  };
  organization: {
    agentSpaceRef: RecordRef & {
      kind?: "agent_space";
      [k: string]: unknown;
    };
    arenaRef:
      | (RecordRef & {
          kind?: "arena";
          [k: string]: unknown;
        })
      | null;
    aboutYawnRefs: (RecordRef & {
      kind?: "yawn";
      [k: string]: unknown;
    })[];
  };
  questionStatus: "open";
  proposalStatus: "proposed";
  createdAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ArtBriefV1".
 */
export interface ArtBriefV1 {
  schemaVersion: "yawn.art-brief.v1";
  briefId: string;
  revision: number;
  observationRef: RecordRef & {
    kind?: "observation";
    revision: number;
    stateSha256: Sha256;
    [k: string]: unknown;
  };
  questionProposalRef: RecordRef & {
    kind?: "question_proposal";
    revision: number;
    stateSha256: Sha256;
    [k: string]: unknown;
  };
  proposedBy: RecordRef & {
    kind?: "actor" | "principal";
    [k: string]: unknown;
  };
  visualIntention: string;
  identityAsset: {
    recordRef: RecordRef & {
      kind?: "source";
      [k: string]: unknown;
    };
    sha256: Sha256;
    crop: "face_only" | "full_body" | "none";
    role: "reflective_agent_not_authority";
  };
  textPolicy: {
    questionRenderedAsPixels: false;
    liveTextRequired: true;
  };
  accessibleDescription: string;
  semanticColorRoles: {
    observation: string;
    question: string;
    agent: string;
  };
  /**
   * @minItems 1
   */
  compositionRequirements: [string, ...string[]];
  negativeConstraints: string[];
  render: {
    width: number;
    height: number;
    seed: number;
    maxCandidates: 1;
  };
  boundary: {
    effectGrantRequired: true;
    externalNetworkEgressAuthorized: false;
    paidProviderCallAuthorized: false;
    maximumPaidCostMicrousd: 0;
    canonicalMutationAuthorized: false;
    publicationAuthorized: false;
    promotionAuthorized: false;
  };
  proposalStatus: "proposed";
  createdAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ProjectionFeedbackV1".
 */
export interface ProjectionFeedbackV1 {
  schemaVersion: "yawn.projection-feedback.v1";
  feedbackId: string;
  ontologyRole: "proposal_facet";
  assertedBy: RecordRef & {
    kind?: "actor" | "principal";
    [k: string]: unknown;
  };
  source: {
    coordinate: string;
    coordinateKind: "local_handoff" | "browser_capture" | "synthetic_fixture";
    platformMessageIdVerified: false;
    exactQuote: string;
    capturedAt: Timestamp;
  };
  subjectRef: RecordRef & {
    kind?: "view";
    [k: string]: unknown;
  };
  /**
   * @minItems 1
   */
  expectedExperience: [
    {
      text: string;
      assertedBy: string;
      epistemicStatus: "reported";
    },
    ...{
      text: string;
      assertedBy: string;
      epistemicStatus: "reported";
    }[]
  ];
  /**
   * @minItems 1
   */
  actualProjectionEvidence: [
    {
      description: string;
      evidenceRef: RecordRef;
      verificationStatus: "reported_not_independently_verified";
    },
    ...{
      description: string;
      evidenceRef: RecordRef;
      verificationStatus: "reported_not_independently_verified";
    }[]
  ];
  /**
   * @minItems 1
   */
  divergenceDimensions: [
    (
      | "testing_fidelity"
      | "ontology_to_interface_fidelity"
      | "source_to_projection_traceability"
      | "accessible_question_fidelity"
      | "visual_identity_fidelity"
      | "iteration_memory"
    ),
    ...(
      | "testing_fidelity"
      | "ontology_to_interface_fidelity"
      | "source_to_projection_traceability"
      | "accessible_question_fidelity"
      | "visual_identity_fidelity"
      | "iteration_memory"
    )[]
  ];
  /**
   * @minItems 1
   */
  preferenceUpdateProposals: [
    {
      preferenceProposalId: string;
      scopeRef: RecordRef;
      viewKind: string;
      fieldPath: string;
      operation: "set" | "reset";
      value: unknown;
      status: "proposed";
      rationale: string;
      sourceFeedbackId: string;
    },
    ...{
      preferenceProposalId: string;
      scopeRef: RecordRef;
      viewKind: string;
      fieldPath: string;
      operation: "set" | "reset";
      value: unknown;
      status: "proposed";
      rationale: string;
      sourceFeedbackId: string;
    }[]
  ];
  /**
   * @minItems 1
   */
  proofObligations: [
    {
      obligationId: string;
      preconditions: string[];
      prediction: string;
      postconditions: string[];
      verifier: string;
      falsifier: string;
      status: "waiting";
    },
    ...{
      obligationId: string;
      preconditions: string[];
      prediction: string;
      postconditions: string[];
      verifier: string;
      falsifier: string;
      status: "waiting";
    }[]
  ];
  epistemicStatus: "reported";
  universality: "subjective_attributed_evaluation";
  proposalStatus: "proposed";
  boundary: {
    canonicalMutationAuthorized: false;
    automaticPreferenceApplicationAuthorized: false;
    publicationAuthorized: false;
    promotionAuthorized: false;
  };
  createdAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "YawnEvent".
 */
export interface YawnEvent {
  id: Uuid;
  agentSpaceId: Uuid;
  yawnId: Uuid | null;
  streamKey: string;
  revision: number;
  eventType: string;
  actorId: string;
  proposalId: Uuid | null;
  payload: {
    [k: string]: unknown;
  };
  previousStateSha256: Sha256 | null;
  resultingStateSha256: Sha256;
  occurredAt: Timestamp;
}
/**
 * This interface was referenced by `YAWNContractsV1`'s JSON-Schema
 * via the `definition` "ProofReceipt".
 */
export interface ProofReceipt {
  id: Uuid;
  yawnId: Uuid;
  preconditions: {
    [k: string]: unknown;
  };
  prediction: string;
  postconditions: {
    [k: string]: unknown;
  };
  verifier: string;
  falsifier: string;
  sourceRefs: SourceSpan[];
  status: "waiting" | "passed" | "failed" | "blocked";
  createdAt: Timestamp;
}
